# Generated by Django 4.0 on 2022-01-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_followinglist_followerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_impressions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visits',
            field=models.BigIntegerField(default=0),
        ),
    ]
