# Generated by Django 4.0 on 2022-01-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='post',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='post',
            field=models.ManyToManyField(to='content.Post', verbose_name='bookmarks'),
        ),
    ]
