# Generated by Django 4.0 on 2022-01-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_bookmark_post_bookmark_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='content.Post', verbose_name='bookmarks'),
        ),
    ]
