# Generated by Django 4.0 on 2022-01-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_bookmark_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='post',
            field=models.ManyToManyField(blank=True, to='content.Post', verbose_name='bookmarks'),
        ),
    ]
